apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      serviceAccountName: fastapi-demo-sa
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: fastapi
          image: k3d-devenv-registry:5000/fastapi-demo:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DEPLOYMENT_ENVIRONMENT
              value: "production"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector.jaeger:4318"
          # Adjusted probe timings to be less aggressive
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "500m"
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
            - name: home
              mountPath: /home/nonroot
              readOnly: false
            - name: sqlite-data
              mountPath: /code/data
              readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}
        - name: home
          emptyDir: {}
        - name: sqlite-data
          emptyDir: {}
