apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
        - name: fastapi
          image: k3d-devenv-registry:5000/fastapi-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DEPLOYMENT_ENVIRONMENT
              value: "production"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector.jaeger:4318"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
