apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
spec:
  selector:
    app: fastapi-demo
  ports:
    - name: http
      port: 8000 # Service port
      targetPort: 8000 # Container port
  type: ClusterIP
