apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: fastapi-demo
